### ISSUE TITLE
Trouble uninstalling with circular dependencies

### ISSUE THREAD

**Issue by jgottwig** [UMD-Digital/umd_terp_base#1]
During development, I've had some issues with uninstalling umd_terp modules (and in some cases, installing). It looks like umd_terp_base depends on most (if not all) ut_* modules, which have a reverse dependency on umd_terp_base. I've been getting around this by removing the ut_* dependencies from umd_terp_base and everything seems to work fine. Maybe it would be ideal if the umd_terp_base submodules depended on umd_terp_base but not vice-versa?

**Comment by magnessjo** [comment]
Hi @jgottwig,

Yes,  all the modules from `umd_terp_base` are required for `umd_terp`.  The theme requires the expected fields from the base. 

If you are removing some dependencies from the base, then my recommendation would be to fork both repos and customize them to your needs.

**Comment by drogers98** [comment]
I believe release 8.1.54 actually solves this issue, just to note for posterity.
