### ISSUE TITLE
Upgrade path?

### ISSUE THREAD

**Issue by jgottwig** [UMD-Digital/umd_terp_base#2]
We are looking to upgrade some of our older sites using umd_terp/base to the more recent codebase, but it doesn't appear as if there is an upgrade path? When I tried locally, I got this error:

`Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "umd_terp_base.edit_button". in Drupal\Component\DependencyInjection\Container->get() (line 153 of /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php).`

I ended up deciding to uninstall and reinstall the umd_terp_base modules.

This did make us wonder if there was an upgrade path documented somewhere, which I should have followed or if the umd_terp/base framework is not intended for upgrading after the initial install? It's also worth noting that we are somewhat early adopters, so it's possible upgrades are more seamless now.

Anyway, we're just trying to get a sense of what to expect when it comes to upgrading.

**Comment by magnessjo** [comment]
Hi @jgottwig ,

This codebase is considered stable.  It is not in active development anymore.  We don't foresee any major (or even minor) updates coming. 

The third-party vendor who to built this module modified the codebase ~ November to bundle the configuration for the fields into the module.  The issues that you are seeing are probably related to that.  For more [context](https://github.com/UMD-Digital/umd_terp_base/commit/11744e0e5f1de2c1369125db5aa2bf23f273885d)

There is not documentation on upgrading as we don't envision additional updates anytime soon.

**Comment by jgottwig** [comment]
Thank you -- I did determine that we could update by manually updating the site with the Events YAML configuration from the umd_terp Content Types module.
