### ISSUE TITLE
Images in News stories URL is incorrect

### ISSUE THREAD

**Issue by gdouglasumd** [UMD-Digital/umd_terp_base#6]
Images in News stories URL is incorrect. For example at the bottom of the page https://essr.umd.edu/news

**Comment by drogers98** [comment]
This appears to be happening at line 29 of https://github.com/UMD-Digital/umd_terp_base/blob/master/modules/ut_news/templates/paragraph--ut-news.html.twig

My guess here is, that today.umd.edu has changed their API to include the full URL. Previously, they did not.

**Comment by gdouglasumd** [comment]
I just noticed it when we updated the theme. I see that
https://today.umd.edu is being repeated in the url
I usually do not go to our actual news page that often, so do not know when
it changed.

I see that https://research.umd.edu/news is also having the same issue.

We are seeing it at the following URLs as well
https://sustainability.umd.edu/
https://sustainability.umd.edu/news

Greg Douglass
IT Manager
University of Maryland
Department of Environmental Safety, Sustainability and Risk
Seneca Building | 4716 Pontiac Street, Suite 0103 | College Park, MD 20742
tel 301.405.0330
he/him/his
www.essr.umd.edu

**Comment by drogers98** [comment]
Correct, that is my assessment as well, the additional examples provided reinforce that

- The last update to the news feed code that sets this was back in 2021 (https://github.com/UMD-Digital/umd_terp_base/commit/40634559b8ac728407b2ba571e4d4b1e17bcd034) So do not think it was related to the code update at all.
- My guess is, the API return from today.umd.edu may have changed image paths from relative (ie '/path/to/my/image', to absolute (ie 'https://my.site.edu/path/to/my/image). We would need to check a few example API returns to confirm, and possible check with stratcom in order to adjust

I have pinged my project manager to check in with UMD DIT to see if they wish to look into this. Thanks for reporting!

**Comment by dbaniszewskiumd** [comment]
> Correct, that is my assessment as well, the additional examples provided reinforce that
> 
>     * The last update to the news feed code that sets this was back in 2021 ([4063455](https://github.com/UMD-Digital/umd_terp_base/commit/40634559b8ac728407b2ba571e4d4b1e17bcd034)) So do not think it was related to the code update at all.
> 
>     * My guess is, the API return from today.umd.edu may have changed image paths from relative (ie '/path/to/my/image', to absolute (ie 'https://my.site.edu/path/to/my/image). We would need to check a few example API returns to confirm, and possible check with stratcom in order to adjust
> 
> 
> I have pinged my project manager to check in with UMD DIT to see if they wish to look into this. Thanks for reporting!

A commit has been made to fix the link by removing the extra domain, https://github.com/UMD-Digital/umd_terp_base/commit/37ae28d86561b83a75374077b891a91f515e1f45

How would we go about requesting a new version release so that our sites will pull down the update?

**Comment by dbaniszewskiumd** [comment]
Thank you.

**Comment by drogers98** [comment]
@dbaniszewskiumd ill get you a release by cob today, just need to adjust something real quick. Thanks all for the help on this

**Comment by dbaniszewskiumd** [comment]
API changed, wasn't UMD Terp code. Thanks for your quick responses on
this.  Tomorrow is fine if something comes up.

Thank you,

*David Baniszewski*
IT Systems Administrator
Division of Information Technology
University of Maryland, College Park

**Comment by drogers98** [comment]
No worries, release 8.1.67 (latest release) has this fix enacted. @gdouglasumd if you update to the latest release, this should be fixed for you.
